name: Preprocessing Dataset

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Up Python 3.12.9
        uses: actions/setup-python@v4
        with:
          python-version: "3.12.9"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas scikit-learn

      - name: Check repository structure
        run: |
          echo "📁 Repository structure:"
          echo "Root directory:"
          ls -la
          
          echo -e "\n📄 Checking for raw dataset:"
          if [ -f "house_dataset_raw.csv" ]; then
            echo "✓ Found house_dataset_raw.csv"
            echo "  File size: $(du -h house_dataset_raw.csv | cut -f1)"
            echo "  Preview (first 5 lines):"
            head -5 house_dataset_raw.csv | sed 's/^/    /'
          else
            echo "❌ house_dataset_raw.csv not found"
            exit 1
          fi
          
          echo -e "\n📁 Preprocessing directory:"
          if [ -d "preprocessing" ]; then
            ls -la preprocessing/
            
            # Check for preprocessing script
            if [ -f "preprocessing/automate_Shalsabilla-Amanda-Putri.py" ]; then
              echo "✓ Found preprocessing script"
            else
              echo "❌ automate_Shalsabilla-Amanda-Putri.py not found in preprocessing directory"
              exit 1
            fi
          else
            echo "❌ preprocessing directory not found"
            exit 1
          fi

      - name: Run data preprocessing
        working-directory: preprocessing
        run: |
          echo "🔄 Starting data preprocessing..."
          
          # Check if automate script exists
          if [ -f "automate_Shalsabilla-Amanda-Putri.py" ]; then
            echo "Running automate_Shalsabilla-Amanda-Putri.py..."
            python automate_Shalsabilla-Amanda-Putri.py
            
            # Check if script ran successfully
            if [ $? -eq 0 ]; then
              echo "✅ Preprocessing script completed successfully"
            else
              echo "❌ Preprocessing script failed"
              exit 1
            fi
          else
            echo "❌ automate_Shalsabilla-Amanda-Putri.py not found"
            exit 1
          fi

      - name: Commit processed data
        run: |
          git config --global user.name "${{ secrets.USERNAME }}"
          git config --global user.email "${{ secrets.EMAIL }}"
          
          # Check if processed data has changed
          if git diff --quiet preprocessing/house_dataset_processed.csv; then
            echo "ℹ No changes detected in processed data"
          else
            # Add processed data
            git add preprocessing/house_dataset_processed.csv
            
            # Commit the changes
            git commit -m "🤖 Auto-update: Dataset preprocessing completed
            
            - Workflow: ${{ github.workflow }}
            - Run: ${{ github.run_id }}
            - Commit: ${{ github.sha }}
            - Timestamp: $(date -u +'%Y-%m-%d %H:%M:%S UTC')
            
            [skip ci]"
            
            git push
            echo "✅ Processed data committed to repository"
          fi